//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CV_PROJECT.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DbCvEntities : DbContext
    {
        public DbCvEntities()
            : base("name=DbCvEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TBL_ADMIN> TBL_ADMIN { get; set; }
        public virtual DbSet<TBL_DENEYIM> TBL_DENEYIM { get; set; }
        public virtual DbSet<TBL_EGITIM> TBL_EGITIM { get; set; }
        public virtual DbSet<TBL_HAKKIMDA> TBL_HAKKIMDA { get; set; }
        public virtual DbSet<TBL_HOBI> TBL_HOBI { get; set; }
        public virtual DbSet<TBL_ILETISIM> TBL_ILETISIM { get; set; }
        public virtual DbSet<TBL_SERTIFIKA> TBL_SERTIFIKA { get; set; }
        public virtual DbSet<TBL_YETENEK> TBL_YETENEK { get; set; }
    }
}
